config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to: 'homes#top'
    resources :managements, only: [:edit]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:new, :index, :show,:edit]
  end
  
  scope module: :public do
    root to: 'homes#top'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :bookmarks, only: [:index, :create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'users/my_page'
    patch 'users/quit'
    resources :users, only: [:index, :show, :edit, :update] do
      resources :follows, only: [:create, :destroy]
        get "followings" => "follows#followings", as: "followings"
        get "followers" => "follows#followers", as: "followers"
    end
    get "search" => "searchs#search"
    
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image
  
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  
  validates :shop_genre, presence: true
  validates :shop_name, presence: true
  validates :address, presence: true
  validates :post_image, presence: true, allow_blank: true
  validates :posting_text, presence: true
  
  enum shop_genre: { food: 0, apparel: 1, beauty: 2, entertainment: 3, leisure: 4, hotel: 5, real_estate: 6, besides: 7 }
  
  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end
  
  # 検索機能
  scope :search_by_column, ->(column, text) { where("#{column} LIKE ?", "%#{text}%") }
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
  end

  def index
    @posts = Post.page(params[:page]).per(15)
  end
  
  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def edit
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<h1>Admin::Posts#edit</h1>
<p>Find me in app/views/admin/posts/edit.html.erb</p>

app/views/admin/posts/index.html.erb
<div class="mx-auto" style="width: 600px;">
  <h1 class="text-center">投稿一覧</h1>
  
  <!--投稿一覧-->
<% @posts.each do |post| %>
  <% if post.post_image.present? %>
    <div class="m-1 border border-dark">
      <%= link_to admin_post_path(post.id), style: "color: black; text-decoration: none;" do %>
        <div class="d-flex border-bottom border-secondary align-items-center">
          <p class="m-1"><%= image_tag post.user.get_icon_image(100,100) %></p>
          <h4 class="m-1"><%= post.user.user_name %></h4>
        </div>
        <div class="d-flex">
          <p class="m-1 font-weight-bold" style="width: 150px;">ショップジャンル</p>
          <p class="m-1"><%= post.shop_genre_i18n %></p>
        </div>
        <div class="d-flex">
          <p class="m-1 font-weight-bold" style="width: 150px;">店舗名</p>
          <p class="m-1"><%= post.shop_name %></p>
        </div>
        <div class="d-flex">
          <p class="m-1 font-weight-bold" style="width: 150px;">住所</p>
          <p class="m-1"><%= post.address %></p>
        </div>
        <div>
          <p class="m-1 text-center"><%= image_tag post.post_image, size: "500x500" %></p>
        </div>
        <div>
          <p class="m-1 font-weight-bold" style="width: 150px;">テキスト</p>
          <p class="mx-1 p-1 border" style="width: auto; height: 100px;"><%= post.posting_text %></p>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="m-1 border border-dark">
      <%= link_to admin_post_path(post.id), style: "color: black; text-decoration: none;" do %>
        <div class="d-flex border-bottom border-secondary align-items-center">
          <p class="m-1"><%= image_tag post.user.get_icon_image(100,100) %></p>
          <h4 class="m-1"><%= post.user.user_name %></h4>
        </div>
        <div class="d-flex">
          <p class="m-1 font-weight-bold" style="width: 150px;">ショップジャンル</p>
          <p class="m-1"><%= post.shop_genre_i18n %></p>
        </div>
        <div class="d-flex">
          <p class="m-1 font-weight-bold" style="width: 150px;">店舗名</p>
          <p class="m-1"><%= post.shop_name %></p>
        </div>
        <div class="d-flex">
          <p class="m-1 font-weight-bold" style="width: 150px;">住所</p>
          <p class="m-1"><%= post.address %></p>
        </div>
        <div>
          <p class="m-1 font-weight-bold" style="width: 150px;">テキスト</p>
          <p class="mx-1 p-1 border" style="width: auto; height: 100px;"><%= post.posting_text %></p>
        </div>
      <% end %>
    </div>  
  <% end %>
  
  <!--ページネーション-->
  <div class="p-1">
    <%= paginate @posts %>
  </div>
  
<% end %>
</div>  

app/views/admin/posts/new.html.erb
<h1>Admin::Posts#new</h1>
<p>Find me in app/views/admin/posts/new.html.erb</p>

app/views/admin/posts/show.html.erb
<div class="mx-auto" style="width: 600px;">
  <h1 class="text-center">投稿詳細</h1>
  
  <!--ユーザー情報-->
  <div class="m-1 border border-dark">
    <%= link_to admin_user_path(@user.id), style: "color: black; text-decoration: none;" do %>
      <div class="d-flex align-items-center">
        <span class="m-1"><%= image_tag @user.get_icon_image(100,100) %></span> 
        <h4 class="m-1"><%= @user.user_name %></h4>
      </div>
    <% end %>
  </div>    

  <!--投稿詳細-->
  <div>
    <% if @post.post_image.present? %>
      <div class="d-flex">
        <p class="m-1 font-weight-bold" style="width: 150px;">ショップジャンル</p>
        <p class="m-1"><%= @post.shop_genre_i18n %></p>
      </div>
      <div class="d-flex">
        <p class="m-1 font-weight-bold" style="width: 150px;">店舗名</p>
        <p class="m-1"><%= @post.shop_name %></p>
      </div>
      <div class="d-flex">
        <p class="m-1 font-weight-bold" style="width: 150px;">住所</p>
        <p class="m-1"><%= @post.address %></p>
      </div>
      <div>
        <p class="text-center"><%= image_tag @post.post_image, size: "500x500" %></p>
      </div>
      <div>
        <p class="m-1 font-weight-bold" style="width: 150px;">テキスト</p>
        <p class="mx-1 p-1 border" style="width: auto; height: 100px;"><%= @post.posting_text %></p>
      </div>
    <% else %>
      <div class="d-flex">
        <p class="m-1 font-weight-bold" style="width: 150px;">ショップジャンル</p>
        <p class="m-1"><%= @post.shop_genre_i18n %></p>
      </div>
      <div class="d-flex">
        <p class="m-1 font-weight-bold" style="width: 150px;">店舗名</p>
        <p class="m-1"><%= @post.shop_name %></p>
      </div>
      <div class="d-flex">
        <p class="m-1 font-weight-bold" style="width: 150px;">住所</p>
        <p class="m-1"><%= @post.address %></p>
      </div>
      <div>
        <p class="m-1 font-weight-bold" style="width: 150px;">テキスト</p>
        <p class="mx-1 p-1 border" style="width: auto; height: 100px;"><%= @post.posting_text %></p>
      </div>
    <% end %>
  </div>
  
  <!--コメント欄-->
  <h3>コメント</h3>
  <div class="m-1 border border-dark">
    <% @post.comments.each do |comment| %>
      <div class="d-flex align-items-center">
        <p class="m-1"><%= image_tag @user.get_icon_image(100,100) %></p>
        <p class="m-1"><%= @user.user_name %></p>
      </div>
        <p class="m-1 border" style="width: auto; height: 100px;"><%= comment.comment %></p>
    <% end %>
  </div>

</div>