config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to: 'homes#top'
    resources :managements, only: [:edit]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:new, :index, :show,:edit]
  end
  
  scope module: :public do
    root to: 'homes#top'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :bookmarks, only: [:index, :create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'users/my_page'
    patch 'users/quit'
    resources :users, only: [:index, :show, :edit, :update] do
      resources :follows, only: [:create, :destroy]
        get "followings" => "follows#followings", as: "followings"
        get "followers" => "follows#followers", as: "followers"
    end
    get "search" => "searchs#search"
    
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :user_name, presence: true
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :comment_posts, through: :comments, source: :post
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post
  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: "followee_id", dependent: :destroy
  has_many :followers, through: :passive_follows, source: :follower
  has_many :followings, through: :active_follows, source: :followee
  
  def active?
    is_active
  end
  
  has_one_attached :icon_image
  def get_icon_image(width, height)
    unless icon_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      icon_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    icon_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # フォロー機能
  def follow(user)
    active_follows.create(followee_id: user.id)
  end
  
  def unfollow(user)
    active_follows.find_by(followee_id: user.id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  
  # 検索機能
  def self.search_for(content, method)
    if method == "perfect"
      User.where(user_name: content)
    elsif method == "forward"
      User.where("user_name LIKE ?", content + "%")
    elsif method == "backward"
      User.where("user_name LIKE ?", "%" + content)
    elsif search == "partial_match"
      User.where("user_name LIKE ?", "%" + content + "%")
    else
      User.all
    end
  end

 

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user.id)
  end

  private
  
  def user_params
    params.require(:user).permit(:user_name, :profile, :is_active)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="mx-auto" style="width: 600px;">
  <h1 class="text-center"><%= @user.user_name %>さんのユーザー情報編集</h1>
  
  <div class="d-flex">
    <p class="m-1 font-weight-bold">アカウント名</p>
    <p class="m-1"><%= @user.user_name %></p>
  </div>
  
  <div class="d-flex">
    <p class="m-1 font-weight-bold">アイコン画像</p>
    <p class="m-1"><%= image_tag @user.get_icon_image(100, 100) %></p>
  </div>
  
  <div class="d-flex">
    <p class="m-1 font-weight-bold">プロフィール</p>
    <p class="m-1"><%= @user.profile %></p>
  </div>

  <div class="d-flex">
    <p class="m-1 font-weight-bold">メールアドレス</p>
    <p class="m-1"><%= @user.email %></p>
  </div>
  
  
  <%= form_with model: @user, url: admin_user_path(@user) do |f| %>
    <div class="field d-flex">
      <p class="m-1 font-weight-bold">ユーザーステータス</p>
      <p class="m-1"><%= f.radio_button :is_active, "true" %></p>
      <p class="m-1"><%= f.label :is_active, "有効" %></p>
      <p class="m-1"><%= f.radio_button :is_active, "false" %></p>
      <p class="m-1"><%= f.label :is_active, "無効" %></p>
    </div>
    <%= f.submit '変更を保存', class: 'btn btn-danger' %>
  <% end %>
  
</div>

app/views/admin/users/index.html.erb
<div class="mx-auto" style="width: 600px;">
  <h1 class="text-center">ユーザー一覧</h1>

<!--ユーザー一覧-->
<% @users.each do |user| %>
  <div class="border">
    <%= link_to admin_user_path(user.id), style: "color: black; text-decoration: none;" do %>
      <table>
        <tr>
          <td><%= image_tag user.get_icon_image(100, 100) %></td>
          <td><%= user.user_name %></td>
        </tr>
      </table>
    <% end %>
  </div>
<% end %>

  <div class="p-1">
    <%= paginate @users %>
  </div>
  
</div>

app/views/admin/users/show.html.erb
<div class="mx-auto" style="width: 600px;">
  <h1 class="text-center">ユーザーページ</h1>

  <!--ユーザー情報-->
  <div class="row">
    <span class="col-2"><%= image_tag @user.get_icon_image(100,100) %></span>
  </div>
  <table style="width: 100%;">
    <tr>
      <td class="m-1 border-bottom font-weight-bold" style="width: 100px;">ユーザー名</td>
      <td class="m-1 border-bottom"><%= @user.user_name %></td>
      <td class="text-right" style="width: 200px;">
        <p><%= link_to "編集", edit_admin_user_path, class: "btn btn-outline-primary" %></p>
      </td>
    </tr>
  </table>
  <div>
    <p class="my-2 border-bottom font-weight-bold" style="width: 100px;">プロフィール</p>
    <p class="p-1 border" style="width: auto; height: 100px;"><%= @user.profile %></p>
  </div>
  
  <!--投稿内容-->
  <div>
    <% @posts.each do |post| %>
      <% if post.post_image.present? %>
        <div class="m-1 border border-dark">
          <%= link_to admin_post_path(post.id), style: "color: black; text-decoration: none;" do %>
            <div class="d-flex">
              <p class="m-1 font-weight-bold" style="width: 150px;">ショップジャンル</p>
              <p class="m-1"><%= post.shop_genre_i18n %></p>
            </div>
            <div class="d-flex">
              <p class="m-1 font-weight-bold" style="width: 150px;">店舗名</p>
              <p class="m-1"><%= post.shop_name %></p>
            </div>
            <div class="d-flex">
              <p class="m-1 font-weight-bold" style="width: 150px;">住所</p>
              <p class="m-1"><%= post.address %></p>
            </div>
            <div>
              <p class="text-center"><%= image_tag post.post_image, size: "500x500" %></p>
            </div>
            <div>
              <p class="m-1 font-weight-bold" style="width: 150px;">テキスト</p>
              <p class="mx-1 p-1 border" style="width: auto; height: 100px;"><%= post.posting_text %></p>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="m-1 border border-dark">
          <%= link_to admin_post_path(post.id), style: "color: black; text-decoration: none;" do %>
            <div class="d-flex">
              <p class="m-1 font-weight-bold" style="width: 150px;">ショップジャンル</p>
              <p class="m-1"><%= post.shop_genre_i18n %></p>
            </div>
            <div class="d-flex">
              <p class="m-1 font-weight-bold" style="width: 150px;">店舗名</p>
              <p class="m-1"><%= post.shop_name %></p>
            </div>
            <div class="d-flex">
              <p class="m-1 font-weight-bold" style="width: 150px;">住所</p>
              <p class="m-1"><%= post.address %></p>
            </div>
            <div>
              <p class="m-1 font-weight-bold" style="width: 150px;">テキスト</p>
              <p class="mx-1 p-1 border" style="width: auto; height: 100px;"><%= post.posting_text %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="p-1">
    <%= paginate @posts %>
  </div>

</div>